### ISSUE TITLE
Issue when using 4 fingers to change desktops

### ISSUE THREAD

**Issue by AhmedDawoud3** [ClementGre/ThreeFingersDragOnWindows#11]
when dragging with 4 fingers to change the desktop, the app reads it as 3 fingers and taps on the screen.

**Comment by ClementGre** [comment]
That's an important issue, I'll work on it when developing the next version !

**Comment by ClementGre** [comment]
This happens because you never places the four fingers at the same time on the touchpad.
Then, a three fingers input is send before you places the fourth finger.

I add a threshold of 100ms, then, the three fingers will not be detected, unless you take a lot of time to add the fourth finger.

Thank you !
