### ISSUE TITLE
Install fails on Windows 10 / 11

### ISSUE THREAD

**Issue by kleuter** [ClementGre/ThreeFingersDragOnWindows#29]
Fails from both msix and app store. Windows 10x64 latest update

![sshot-399](https://github.com/ClementGre/ThreeFingersDragOnWindows/assets/2600624/314cd375-0f10-4c77-a90b-6cd7abf407f1)

**Comment by ClementGre** [comment]
This might be due to the fact that you are using Windows 10 and not Windows 11, then some libraries are missing.
You might be able to solve the issue by installing them manually, but I don't event know what they are.

I'll try to find a way to make a package for windows 10 that includes these needed libraries.

**Comment by kleuter** [comment]
I just checked on Windows 11 - same problem

**Comment by ClementGre** [comment]
Is the install working after installing the Windows App SDK redistributable on this page: [https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads)?

**Comment by kleuter** [comment]
It did help, thank you
